server:
  port: 8080
  host: localhost
database:
  cache:
    redis:
      address: localhost:6379
      password: pass
      db_name: 0
  postgresql:
    host: localhost
    port: 5432
    username: postgres
    password: password
    database: gymtracker
telegram:
  token: 8549316894:AAEcFSX3tGRNI7y8NLmwJWspkJtLntWWt34
  debug: true
  timeout: 10000
  new_update: 0